// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: jbqypeujuowyrajncnnt

class SupabaseConfig {
  static const String supabaseUrl = 'https://jbqypeujuowyrajncnnt.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpicXlwZXVqdW93eXJham5jbm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2ODIwMDEsImV4cCI6MjA4MDI1ODAwMX0.MPWS_YDHBWqu6g57tWpLEIKMjlthjcSYAla75e7LDas';
}
